[project]
name = "hass-intercom"
version = "0.1.0"
description = "Home Assistant compatible intercom system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "simpleaudio @ git+https://github.com/cexen/py-simple-audio.git",
    "sounddevice"
]
